// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"tiktok/api"
	"tiktok/internal/conf"
	"tiktok/internal/data"
	"tiktok/internal/middleware"
	"tiktok/internal/service"
	"tiktok/pkg/logging"
	"tiktok/pkg/util"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, error) {
	logger := logging.NewLogger()
	confData := conf.GetData()
	dataData, err := data.NewData(confData, logger)
	if err != nil {
		return nil, err
	}
	userDao := data.NewUserDao(logger, dataData)
	jwtConfig := conf.GetJwtConf()
	jwtUtil := util.GetJwtUtil(jwtConfig)
	userService := service.NewUserService(logger, userDao, jwtUtil)
	userController := api.NewUserController(logger, userService)
	ossConfig := conf.GetOSSConf()
	ossUtil := util.GetOssUtil(ossConfig)
	videoDao := data.NewVideoDao(logger, dataData)
	videoService := service.NewVideoService(logger, ossUtil, videoDao)
	videoController := api.NewVideoController(logger, ossUtil, jwtUtil, videoService)
	loginCheckMiddleware := middleware.NewLoginCheck(userService, jwtUtil)
	injector := InitInjector(userController, videoController, loginCheckMiddleware)
	return injector, nil
}
